package org.mattlang.jc.movegenerator;

import org.mattlang.jc.board.Color;
import org.mattlang.jc.moves.CastlingMove;

/**
 * Collects moves generated by a MoveGenerator.
 */
public interface MoveCollector {

    /**
     * Reset move list.
     * @param side the side to generate moves for.
     */
    void reset(Color side);

    void genMove(byte figureType, int from, int to, byte capturedFigureCode);

    void genQuietMoves(byte figType, int from, long quietTargets);

    void genPawnMove(int from, int to, byte capturedFigureCode);

    void genPawnQuiets(long targets, int fromOffset);

    void addCastlingMove(CastlingMove castlingMove);

    void genEnPassant(int i, int n, int enPassantCapturePos);

}
