package org.mattlang.jc.movegenerator;

import org.mattlang.jc.board.Color;
import org.mattlang.jc.moves.CastlingMove;

/**
 * Collects moves generated by a MoveGenerator.
 */
public interface MoveCollector {

    void genMove(byte figureType, int from, int to, byte capturedFigureCode);

    void genPawnMove(int from, int to, Color color, byte capturedFigureCode);

    void addCastlingMove(CastlingMove castlingMove);

    void genEnPassant(int i, int n, Color side, int enPassantCapturePos);

}
