when:
  - event: push
    branch: [master, develop, feature/*]

steps:
  - name: build
    image: maven:3.9.9-eclipse-temurin-17
    commands:
      - echo "building project"
#      - mvn clean package
      - mvn clean package install -B -DskipTests -Dmaven.repo.local=/woodpecker/.m2
  - name: unit tests
    image: maven:3.9.9-eclipse-temurin-17
    commands:
      - echo "unit tests"
      - mvn surefire:test -B -Dmaven.repo.local=/woodpecker/.m2
