when:
  - event: push
    branch: [master, develop, feature/*]

steps:
  - name: integration tests
    image: maven:3.9.9-eclipse-temurin-17
    commands:
      - echo "integration tests"
      - mvn clean test-compile surefire:test surefire-report:report-only -B -PallTests
depends_on:
  - build